import Head from 'next/head';
import { NextPage, GetServerSideProps } from 'next';

import { fetcher } from 'src/service/fetcher';

import { MainContainer } from 'styles/common/main-container';
import MainContent from 'components/mainContent/MainContent';

import { IWisdo, IMain } from 'src/types/wisdo';
import { AxiosResponse } from 'axios';

const Main: NextPage<IMain> = ({ wisdoList }) => {
	return (
		<>
			<Head>
				<title>Wisdo</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<MainContainer>
				<MainContent wisdoList={wisdoList} />
			</MainContainer>
		</>
	);
};

export const getServerSideProps: GetServerSideProps = async ({ res }) => {
	try {
		const { data }: AxiosResponse<IWisdo[]> = await fetcher.get('/feed');
		res.setHeader('Cache-Control', `private, s-maxage=1, stale-while-revalidate=18000`);

		return {
			props: {
				wisdoList: data,
			},
		};
	} catch (e) {
		return {
			redirect: {
				permanent: false,
				destination: '/error',
			},
			props: {},
		};
	}
};

export default Main;
